### ISSUE TITLE
PDF user manual failing build

### ISSUE THREAD

**Issue by jason-p-pickering** [dhis2/dhis2-docs#252]
Description
The process 'Apache FOP' ended with code: 1.
The error was: 
ERROR - Couldn't find hyphenation pattern for lang="en".
ERROR - Image not found. URI: /home/jason/development/dhis2-docs/src/docbkx/en/content/maintenance/./attribute/resources/images/maintainence/attribute_create.png. (See position 2136:-1)
ERROR - Image not found. URI: /home/jason/development/dhis2-docs/src/docbkx/en/content/maintenance/./constant/resources/images/maintainence/constant_create.png. (See position 2168:-1)
ERROR - Image not found. URI: /home/jason/development/dhis2-docs/src/docbkx/en/content/maintenance/./option_set/resources/images/maintainence/option_set_create.png. (See position 2203:-1)
ERROR - Image not found. URI: /home/jason/development/dhis2-docs/src/docbkx/en/content/maintenance/./attribute/resources/images/maintainence/attribute_create.png. (No context info available)
ERROR - Image not found. URI: /home/jason/development/dhis2-docs/src/docbkx/en/content/maintenance/./constant/resources/images/maintainence/constant_create.png. (No context info available)
ERROR - Image not found. URI: /home/jason/development/dhis2-docs/src/docbkx/en/content/maintenance/./option_set/resources/images/maintainence/option_set_create.png. (No context info available)
ERROR - net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
ERROR - Exception
org.apache.fop.apps.FOPException: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
    at org.apache.fop.cli.InputHandlerFOP.transformTo(Unknown Source)
    at org.apache.fop.cli.InputHandlerFOP.renderTo(Unknown Source)
    at org.apache.fop.cli.Main.startFOP(Main.java:177)
    at org.apache.fop.cli.Main.main(Main.java:208)
Caused by: net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
    at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(Unknown Source)
    at net.sf.saxon.event.ContentHandlerProxy.startContent(Unknown Source)
    at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:215)
    at net.sf.saxon.event.ReceivingContentHandler.startElement(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.xinclude.XIncludeHandler.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
    at net.sf.saxon.event.Sender.send(Sender.java:146)
    at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
    ... 4 more
Caused by: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
    at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
    at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
    at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
    at com.sun.proxy.$Proxy6.invalidChild(Unknown Source)
    at org.apache.fop.fo.FONode.invalidChildError(FONode.java:561)
    at org.apache.fop.fo.FONode.invalidChildError(FONode.java:537)
    at org.apache.fop.fo.pagination.Root.validateChildNode(Root.java:159)
    at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:265)
    at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:175)
    ... 20 more

---

net.sf.saxon.trans.XPathException: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
    at net.sf.saxon.event.ContentHandlerProxy.handleSAXException(Unknown Source)
    at net.sf.saxon.event.ContentHandlerProxy.startContent(Unknown Source)
    at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:215)
    at net.sf.saxon.event.ReceivingContentHandler.startElement(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.xinclude.XIncludeHandler.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
    at net.sf.saxon.event.Sender.send(Sender.java:146)
    at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
    at org.apache.fop.cli.InputHandlerFOP.transformTo(Unknown Source)
    at org.apache.fop.cli.InputHandlerFOP.renderTo(Unknown Source)
    at org.apache.fop.cli.Main.startFOP(Main.java:177)
    at org.apache.fop.cli.Main.main(Main.java:208)
Caused by: org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
    at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
    at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
    at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
    at com.sun.proxy.$Proxy6.invalidChild(Unknown Source)
    at org.apache.fop.fo.FONode.invalidChildError(FONode.java:561)
    at org.apache.fop.fo.FONode.invalidChildError(FONode.java:537)
    at org.apache.fop.fo.pagination.Root.validateChildNode(Root.java:159)
    at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:265)
    at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:175)
##     ... 20 more

org.apache.fop.fo.ValidationException: "fo:block" is not a valid child of "fo:root"! (See position 5802:-1)
    at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
    at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
    at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)
    at com.sun.proxy.$Proxy6.invalidChild(Unknown Source)
    at org.apache.fop.fo.FONode.invalidChildError(FONode.java:561)
    at org.apache.fop.fo.FONode.invalidChildError(FONode.java:537)
    at org.apache.fop.fo.pagination.Root.validateChildNode(Root.java:159)
    at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:265)
    at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:175)
    at net.sf.saxon.event.ContentHandlerProxy.startContent(Unknown Source)
    at net.sf.saxon.event.NamespaceReducer.startContent(NamespaceReducer.java:215)
    at net.sf.saxon.event.ReceivingContentHandler.startElement(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.xinclude.XIncludeHandler.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:441)
    at net.sf.saxon.event.Sender.send(Sender.java:146)
    at net.sf.saxon.jaxp.IdentityTransformer.transform(IdentityTransformer.java:363)
    at org.apache.fop.cli.InputHandlerFOP.transformTo(Unknown Source)
    at org.apache.fop.cli.InputHandlerFOP.renderTo(Unknown Source)
    at org.apache.fop.cli.Main.startFOP(Main.java:177)
    at org.apache.fop.cli.Main.main(Main.java:208)
Severity
Error
System ID
/home/jason/development/dhis2-docs/src/docbkx/en/dhis2_user_manual_en.xml_xslt
Scenario
DocBook PDF
Document type
DocBook 5
XML file
/home/jason/development/dhis2-docs/src/docbkx/en/dhis2_user_manual_en.xml
XSL file
/home/jason/Oxygen XML Editor 17/frameworks/docbook/xsl/fo/docbook_custom.xsl
Engine name
Apache FOP
Start location
line: 2136, column: 0
Additional info
More details

**Comment by ceciliapersson** [comment]
@jason-p-pickering Does this issue pertain to the xml:id issues we had two weeks ago? Can I close the issue?

**Comment by jason-p-pickering** [comment]
Seems to be solved for now.
